version: "3.8"
services:
  todo-app:
    build: .
    container_name: todo_app
    ports:
      - "3600:3600"
    restart: always
    environment:
      MONGODB_URI: mongodb://db:27017/mydatabase
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3600"]
      interval: 30s
      timeout: 5s
      retries: 10
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 10

volumes:
  mongodb_data:


    